// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3OREZv3vBU7X9zW9Ik9x9mft34h3YnTM',
    appId: '1:1046480761785:web:83742230f6f8cefbf17c68',
    messagingSenderId: '1046480761785',
    projectId: 'lesson-project-ca22f',
    authDomain: 'lesson-project-ca22f.firebaseapp.com',
    storageBucket: 'lesson-project-ca22f.appspot.com',
    measurementId: 'G-BEC5SG96PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeM67IUIWzv9YeEsZBS165j3TaV7s0pHA',
    appId: '1:1046480761785:android:917a25f28492b7b8f17c68',
    messagingSenderId: '1046480761785',
    projectId: 'lesson-project-ca22f',
    storageBucket: 'lesson-project-ca22f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8mk_RSaRL8QOBeHqgDryDnipr7AmIhrM',
    appId: '1:1046480761785:ios:cb891f65af0d0bbcf17c68',
    messagingSenderId: '1046480761785',
    projectId: 'lesson-project-ca22f',
    storageBucket: 'lesson-project-ca22f.appspot.com',
    iosClientId: '1046480761785-anhavrkm43om152q9qs3c09a6dallnso.apps.googleusercontent.com',
    iosBundleId: 'com.example.lessonProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8mk_RSaRL8QOBeHqgDryDnipr7AmIhrM',
    appId: '1:1046480761785:ios:cb891f65af0d0bbcf17c68',
    messagingSenderId: '1046480761785',
    projectId: 'lesson-project-ca22f',
    storageBucket: 'lesson-project-ca22f.appspot.com',
    iosClientId: '1046480761785-anhavrkm43om152q9qs3c09a6dallnso.apps.googleusercontent.com',
    iosBundleId: 'com.example.lessonProject',
  );
}
